### ISSUE TITLE
Extra subscription

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#37]
User: Steve Burge<br>Joomla: <br>Subscriptions: <br>- PWT ACL - Personal / until: 2019-05-18<br>- PWT ACL - Agency / until: 2018-02-13<br>- PWT ACL - Agency / until: 2016-10-26<br><hr>Hey guys. In your ACL 3.0 launch post, you mentioned a bonus subscription. I didn't see the offer, but would love to test PWTSEO.

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hi Steve,

Thanks for reporting the issue. The free gift selection should be visible on your dashboard now. Enjoy PWT SEO!

Sander

**Comment by pwtextensions** [comment]
Thanks Sander. Have a great weekend and all the best with this re-launch
