### ISSUE TITLE
Renewal discount

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#38]
User: Calvin Toy<br>Joomla: <br>Subscriptions: <br>- PWT ACL - Agency / until: 2018-04-12<br>- PWT ACL - Agency / until: 2017-01-07<br><hr>I missed any renewal reminder email for ACL Manager last month.  Do I need to purchase a new subscription, or can I renew with the 20% discount?

My email is panda99a@hotmail.com 

Thanks.

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hi Calvin,

If you visit the website via https://extensions.perfectwebteam.com/?coupon=ACLRENEWAL you can renew your subscription with the 20% discount.

Sander
