### ISSUE TITLE
design foutje in ticket systeem

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#39]
User: HAns Hardeman<br>Joomla: <br>Subscriptions: <br>- PWT Image - Free Gift / until: 2018-06-22<br>- PWT SEO - Business / until: 2019-02-19<br>- PWT ACL - Business / until: 2019-01-10<br>- PWT ACL - Agency / until: 2015-10-01<br><hr>ik zie  dit boven mijn berichten staan

Posted woensdag 23 mei 2018 14:23 by HAns Hardeman

echter nergens in het systeem heb ik HAns ingegeven,  waar komt die A vandaan. die een a moet zijn, 
Succes met zoeken

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hallo Hans,

In ons systeem stond je naam wel degelijk met een hoofdletter A. Dit heb ik nu aangepast dus de weergave in het ticket systeem zou ook weer goed moeten zijn.

Sander

**Comment by pwtextensions** [comment]
Ok dank voor het aanpassen, echter bij het bekijken van het profiel stond het goed, blijkbaar nog een ander deel wat voor mij niet zichtbaar is?

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hallo Hans,

Dank voor het wijzen op het probleem. Je profiel in het subscription systeem was wel bijgewerkt, maar niet je de naam van je Joomla account op onze site. Dit probleem is nu verholpen dus toekomstige aanpassingen komen wel op alle plekken door.

Sander

**Comment by pwtextensions** [comment]
Ok, graag gedaan mbt er op wijzen, en fijn dat het opgelost is,
Ik vindt een ticketsysteem soms lastig, wanneer  stop je met een onder werp en wie stopt er,  persoonlijk heb ik er moeite mee als ik van mijn klanten een vraag krijg, die beantwoord en dan nooit meer wat hoor 
vandaar de volgende regel waar ik mee afsluit
over en uit
