### ISSUE TITLE
Where do I change my password?

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#40]
User: Phil Walton<br>Joomla: <br>Subscriptions: <br>- PWT Sitemap - Agency / until: 2018-12-21<br>- PWT ACL - Agency / until: 2018-11-19<br>- PWT Image - Agency / until: 2018-11-19<br>- PWT SEO - Agency / until: 2018-11-19<br>- PWT ACL - Agency / until: 2017-11-12<br><hr>Hi, I tried my account page and it allows all to be change apart from my password... Where can I change my password?

**Comment by pwtextensions** [comment]
Found it, I had to look through your site map... Is it anywhere else? Thats a little hidden

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hi Phil,

Glad you found it. It's on the list to add to the account page as well.

Sander
