### ISSUE TITLE
tax residence certificate? 

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#41]
User: Brand Piotr Czuryłło  <br>Joomla: <br>Subscriptions: <br>- PWT Image - Free Gift / until: 2018-06-22<br>- PWT ACL - Agency / until: 2019-04-11<br><hr>Could you send a tax residence certificate?

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hi Brand,

I am not sure what you are looking for, could you please explain? Thanks!

Sander
