### ISSUE TITLE
Watchful PWT Extensions Download Key

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#43]
User: Richard Sparks<br>Joomla: <br>Subscriptions: <br>- PWT SEO - Business / until: 2018-11-18<br>- PWT ACL - Agency / until: 2019-06-16<br>- PWT ACL - Agency / until: 2014-06-17<br><hr>My Watchful account still only shows an option for ACL Manager Download Key in their License Keys tab. Is it just me or have they not updated it yet?

Richard Sparks

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hi Richard,

Hope you are fine! We have requested Watchful a few weeks ago to change the label of the downloads key to PWT Extensions. Unfortunately, this is not changed yet. 

Sander
