### ISSUE TITLE
Renew my subscription

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#44]
User: Navid Raeisi<br>Joomla: <br>Subscriptions: <br>- PWT ACL - Agency / until: 2017-12-31<br><hr>Dear Sander Potjer, 

Hello
I am Navid Raeisi from joomla.ir. I have already worked with aclmanager.net as a Persian language extension.

I would like to ask you to let me have access to the website components and be able to download and localize them.

Best regards

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hi Navid,

Your subscription is active again. Looking forward to the updated translations.

Sander
