### ISSUE TITLE
Delete user account

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#45]
User: Martin Scholtes<br>Joomla: <br>Subscriptions: <br>- PWT ACL - Agency / until: 2016-10-19<br><hr>Hello,
please delete my user account with the e-mail address "mail@martin-scholtes.de" and all data related to this e-mail address.

Thank you very much

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hi Martin,

Your account is deleted.

Sander
