### ISSUE TITLE
ACL manager

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#46]
User: Charpie Jacques<br>Joomla: <br>Subscriptions: <br>- PWT ACL - Agency / until: 2017-09-29<br>- PWT ACL - Agency / until: 2012-09-30<br><hr>Hi, I'm responsible of 2 or 3 non profit organization websites. I had a subscription to ACL manager which I used for checking the sites permissions as well as Assets tables.

My subscription is not valid anymore. Before upgrading to PWT ACL, I want to ask if I may install your extension on more than one site

best regards

Jacques

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hi Charpie,

Yes, you can install PWT ACL on as many sites as you want.

Sander

**Comment by pwtextensions** [comment]
That's great. 
I order your extension
