### ISSUE TITLE
Update demo website

### ISSUE THREAD

**Issue by sanderpotjer** [perfectwebteam/pwtextensions#47]
- [x] PWT ACL 3.0.1, graag ook in de demo site nu, niet langer aclmanagerdemo.net
- [x] PWT SEO 1.2.1 (bij elmar vragen)
- [x] PWT Image 1.2.0 (even zelf build doen)
- [x] PWT Sitemap 1.1.1
- [x] Joomla 3.8.10

En graag even beknopte instructies voor bijwerken in toekomst :)

**Comment by roland-d** [comment]
@sanderpotjer Demo is bijgewerkt in de repo https://github.com/perfectwebteam/perfectextensionsdemo
