### ISSUE TITLE
Verdwaald in een rim-ram van reclame.

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#48]
User: Gert Uphoff, Webmaster Korenonline.nl<br>Joomla: <br>Subscriptions: <br>- PWT ACL - Agency / until: 2018-08-06<br>- PWT ACL - Agency / until: 2012-08-07<br><hr>Ik log in om even te kijken tot wanneer mijn abonnement op ACL geldig is en verdwaal in een hoeveelheid van n.b. Engelstalige schermen / plaatjes. 
Gewoon even naar mijn account en mijn abonnementen bekijken bestaat kennelijk niet. 
Ik weet niet wat ACL Agency is. Wel wordt ik prominent geconfronteerd met iets wat ik in 2012 ooit gehad heb. Dat is toch weinig zinvol ...
Nee ik vindt dat m.b.t. gebruikersvriendelijkheid jullie steekjes laten vallen.

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hallo Gert,

Dat is uiteraard jammer om te horen. Het overzicht van je abonnementen staat in je dashboard. Na inloggen op https://extensions.perfectwebteam.com/login kom je daar automatisch terecht (https://extensions.perfectwebteam.com/dashboard). 

Je actieve abonnementen staan direct bovenaan onder het kopje "Active subscriptions". De verlopen staan onder "Expired subscriptions". Daar staat dus inderdaad een subscription uit 2012. Als we die niet tonen vinden mensen dat ook verwarrend, want "waar is dan mijn subscription gebleven dat ik ooit gekocht heb?" krijgen we anders als vraag.

Wat kunnen we anders inrichten om het duidelijker te maken? Heb je daarvoor suggesties? Ik snap ook niet helemaal wat je bedoeld met "rim-ram van reclame".

Dank voor je toelichting.

Sander

**Comment by pwtextensions** [comment]
Hallo Sander. De link uit jouw naar jouw antwoord mail eindigt in een 404 (ik kan de afbeelding daarvan niet toevoegen).
Smaken verschillen. Het zal wel aan mijn leeftijd liggen (73). Ik hou van eenvoud.

Ik begrijp nu dat PWT ACL Agency de extensie is die ik de afgelopen jaren van jullie afgenomen heb.

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hallo Gert,

De link is zichtbaar, maar daarvoor zul je eerst moeten inloggen. Met de overgang van ACL Manager naar PWT Extensions / PWT ACL zijn de subscriptions inderdaad hernoemd naar PWT ACL Agency. Zie ook https://extensions.perfectwebteam.com/aclmanager voor meer informatie.

Sander
