### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#49]
User: Aristeidis Ntatsis<br>Joomla: <br>Subscriptions: <br>- PWT ACL - Business / until: 2019-06-30<br>- PWT ACL - Agency / until: 2018-11-24<br>- PWT Sitemap - Business / until: 2018-11-24<br>- PWT SEO - Business / until: 2018-11-24<br><hr>Hi, i am Aris Ntatsis from Athens/Greece.

I would like to ask you to add Greek Language at Crowdin, and let me translate your extensions.
I am proofreader of the Greek Translation of Joomla Core in Crowdin.
Furthermore, i am using 3 of the 4 PWT extensions.

Regards,

Aris Ntatsis
Onscreen Web Services

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hi Aris,

Thank you for your offer to translate our extensions! We have added the Greek language and added you as proofreader. We have also added a PWT Image subscription to your account.

Thanks in advance for your translations.

Sander

**Comment by pwtextensions** [comment]
Hi Sander,

Thank you for your response.
I will do my best, August is the perfect month for this job.

Btw, it was fine to meet you at Koln, on May.
Regards,
Aris

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hi Aris,

Was very nice to meet you at the pre-event at JAB! :-)

Sander

**Comment by pwtextensions** [comment]
Hi Sander,

I need some help. May i upload the relative el-GR files at crowndin, or just work at Greek translation of the en-GB language files?

Best regards,

Aris Ntatsis

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hi Aris,

The file names are indeed a bit confusing, but you can translate the files on the Greek language page: https://crowdin.com/project/pwt-acl/el#

Sander

**Comment by pwtextensions** [comment]
Thank you, Sander

It is clear to me, now.

Aris
