### ISSUE TITLE
Translations to Swedish

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#50]
User: Stefan Gagner<br>Joomla: <br>Subscriptions: <br>- PWT ACL - Personal / until: 2019-05-19<br>- PWT ACL - Agency / until: 2018-05-12<br>- PWT ACL - Agency / until: 2013-05-12<br><hr>Hi!
I woukld like to translate all your extensions to Swedish language (sv-SE) as profreader.
I have joined the projects on Crowdin but there is no Swedish to translate yet.

**Comment by euismod2336** [comment]
Via Crowdin hierop gereageerd. Sweeds toegevoegd en Stefan als proofreader ingesteld.
