### ISSUE TITLE
proofreader 

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#51]
User: olivier frascone<br>Joomla: <br>Subscriptions: <br>- PWT Image - Agency / until: 2018-12-31<br>- PWT SEO - Business / until: 2018-11-23<br>- PWT ACL - Agency / until: 2018-08-17<br><hr>Hi, just finished the translation of PWTSitemap, i will start the PWT ACL, could you switch my account on crowdin as proofreader ?
Regards,
Olivier

**Comment by euismod2336** [comment]
@pwtextensions 
Hi Olivier,

Following this link: https://crowdin.com/project/pwt-acl/invite?d=55550505b6g5t6o473e3i3j463, should get you into the ACL project. Your account for Sitemap has been changed to proofreader.

Thanks for the translations!

Regards,
Elmar
