### ISSUE TITLE
PWT sitmap Menu error

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#52]
User: Anne Malysse<br>Joomla: <br>Subscriptions: <br>- PWT ACL - Agency / until: 2016-10-04<br>- PWT Sitemap - Free Gift / until: 2018-06-22<br>- PWT ACL - Agency / until: 2018-06-06<br><hr>hi,

Er is een probleem met de Sitemap 1.1.0.
Wanneer ik een menu wil toevoegen of bewerken krijg ik de foutboodschap "Can not use object or type stdClass as array"
mvg,

Erwin

**Comment by euismod2336** [comment]
@pwtextensions 
Hi Erwin,

In de nieuwere versie (1.1.2) is dat issue gefixed! Deze kan je downloaden vanuit je profiel pagina op https://extensions.perfectwebteam.com/

Groet,
Elmar
