### ISSUE TITLE
Download ID / Update Procedure

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#53]
User: Christian Hostettler<br>Joomla: <br>Subscriptions: <br>- PWT SEO - Free Gift / until: 2018-08-11<br>- PWT Sitemap - Agency / until: 2019-07-07<br>- PWT ACL - Agency / until: 2018-08-10<br>- PWT ACL - Agency / until: 2016-05-23<br><hr>Hi PWTTeam
It was very fine the possibility to manage updates with watchfull (https://app.watchful.li/).
Best regards
Chris

**Comment by euismod2336** [comment]
@pwtextensions 
Hi Chris,

As far as I know there is no working integration with Watchfull. But I'll check with some of my colleague's (who work with it daily) what the exact status is and I'll let you know!

Regards,
Elmar

**Comment by euismod2336** [comment]
@pwtextensions 
Hi Chris,

My collegue's confirmed that we're still waiting on Watchfull. There seems to be some internal conflicts which makes the process longer then normal...

Regards,
Elmar

**Comment by pwtextensions** [comment]
Hi Elmar
Ok, thank You for this information, and I will hope on a solution as soon as possible.
best regards, Chris
