### ISSUE TITLE
Agency and Extensions

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#55]
User: Luke Douglas<br>Joomla: <br>Subscriptions: <br>- PWT ACL - Agency / until: 2019-08-06<br>- PWT ACL - Business / until: 2019-02-03<br>- PWT ACL - Agency / until: 2018-01-25<br><hr>On your PWT Image, can you reduce the DPI, ie: 300 dpi to 72 dpi within the editor?
On your pricing, do you have a Agency price for all of your extensions?

**Comment by euismod2336** [comment]
@pwtextensions 
Hi Luke,

Providing an option to set the DPI would be a great addition! I'll put in in the roadmap.

We do provide an Agency bundle, with a 20% discount. You can find that at https://extensions.perfectwebteam.com/pwt-acl/pricing below the 'subscription plans'.

Hope that answers your questions!

Regards,
Elmar

**Comment by pwtextensions** [comment]
Elmar,

Thanks.  I do think the DPI would be great as it would reduce the size of the file and we all know pageload times are critical.

As far as the link to the Agency, I've already subscribed to the Agency for ACL.  What I was referring to was a single Agency subscription for ALL of your extensions, both the ones you have now as well as any you may add in the future.  Do you have that option or is my purchase of the Agency on the ACL particle good for all particles?

Thanks.

**Comment by euismod2336** [comment]
@pwtextensions 
Hi Luke,

I'm still not sure if I know what you mean :)

Your agency subscription only covers PWT ACL, not any of the other extentions. It does however cover an unlimited amount of websites on which you can install it.

Regards,
Elmar

**Comment by pwtextensions** [comment]
Elmar,

Yes, that was what I was referring to.  Having to purchase an Agency level for 'each' product is OK but it would be good to have a BUNDLE of all products with an Agency level, naturally giving a discount overall.  Most sites provide a discount range of 20%-50% of each product when bundled with all others.  

Example:
PWT ACL
Agency 69 Euro

PWT SEO
Agency 179 Euro

PWT Image
Agency 119 Euro

PWT Sitemap
Agency 49 Euro

Total 416 Euro

PWT Bundle
Agency 275 Euro

For me, I would 'highly' consider paying 275 Euro for access to all of your extensions with unlimited use.  I have about 65-70 client websites and that would be worthwhile for my clients and for me.

Just a thought!

**Comment by euismod2336** [comment]
@pwtextensions 
Hi Luke,

Yes, we do have a bundle but it's not as easy accessible as one would hope ;)

The link I've provided, below the subscription plans (this one also works: https://extensions.perfectwebteam.com/pwt-seo/pricing), there's a button to add a bundle subscription to your cart. This gives you an agency subscription on all our extensions with a 20% discount (so it would amount to 333 Euro). I'm not a 100% if the system actually registers that you already have the ACL agency. Let us know if there's any issue with it!

Regards,
Elmar

**Comment by pwtextensions** [comment]
So I have two subscriptions for ACL and they look to be running concurrently.  Shouldn't one have been combined and the date extended?

Also, if I were to get the bundle, do I get credit for everything I have already paid?

**Comment by Martijn-Boomsma** [comment]
@pwtextensions
Hi Luke, 

We will look into what happened with the combination but I think the system currently does not take into account two different kinds of subscriptions, although I agree you would expect some kind of upgrade. I will ask the developer of that system when he gets back from his holidays. What I can do for you now is either:
A. Combine the two current ACL subscriptions to 1 agency, by deactivating the business sub and extend the agency with 6 months
B. Deactivate both current subscriptions and give you a special discount code link for the agency subscription bundle with €100,- as credit for what you have already paid.

Please let us know if that works for you.

Best Regards,
Martijn
