### ISSUE TITLE
Test image upload

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#56]
User: Sander Potjer / info@perfectwebteam.nl<br>Joomla: <br>Subscriptions: <br>- PWT Sitemap - Agency / until: 2018-11-17<br>- PWT SEO - Business / until: 2018-11-17<br>- PWT ACL - Agency / until: 2018-09-05<br>- PWT Image - Personal / until: 2018-06-14<br>- PWT Extensions Agency Bundle / until: 2018-01-31<br><hr>Eens kijken of dit een beetje werkt!<hr>Screenshots: <br>![Screen Shot 2018-08-14 at 11.08.55.png]('https://extensions.perfectwebteam.com/uploads/10500/Screen Shot 2018-08-14 at 11.08.55.png')<br>![Screen Shot 2018-08-14 at 11.08.57.png]('https://extensions.perfectwebteam.com/uploads/10500/Screen Shot 2018-08-14 at 11.08.57.png')<br>

**Comment by sanderpotjer** [comment]
<img width="1269" alt="screen shot 2018-08-14 at 11 08 57" src="https://user-images.githubusercontent.com/522834/44082883-cc541d4e-9fb2-11e8-847a-aa3fa7a3eb29.png">

**Comment by pwtextensions** [comment]
Reactie met afbeelding dan?<hr>Screenshots: <br>![Screen_Shot_2018-08-14_at_11.08.57.png](https://extensions.perfectwebteam.com//uploads/10500/Screen_Shot_2018-08-14_at_11.08.57.png)<br>
