### ISSUE TITLE
Laatste test

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#58]
User: Sander Potjer / info@perfectwebteam.nl<br>Joomla: <br>Subscriptions: <br>- PWT Sitemap - Agency / until: 2018-11-17<br>- PWT SEO - Business / until: 2018-11-17<br>- PWT ACL - Agency / until: 2018-09-05<br>- PWT Image - Personal / until: 2018-06-14<br>- PWT Extensions Agency Bundle / until: 2018-01-31<br><hr>Test of afbeelding nu ook op site zichtbaa ris. 
### Screenshots:
![Screen_Shot_2018-08-14_at_11.08.55.png](https://extensions.perfectwebteam.com//uploads/10500/Screen_Shot_2018-08-14_at_11.08.55.png)<br>

**Comment by pwtextensions** [comment]
Test comment.###Screenshots:<br>![Screen_Shot_2018-08-14_at_11.08.57.png](https://extensions.perfectwebteam.com//uploads/10500/Screen_Shot_2018-08-14_at_11.08.57.png)<br>

**Comment by pwtextensions** [comment]
Hash image<h4>Screenshots:</h4>![d8ef77dc_Screen_Shot_2018-08-14_at_11.08.57.png](https://extensions.perfectwebteam.com//uploads/10500/d8ef77dc_Screen_Shot_2018-08-14_at_11.08.57.png)<br>

**Comment by sanderpotjer** [comment]
@pwtextensions 
Benieuwd, werkt afbeelding van Github nu ook?

<img width="427" alt="screen shot 2018-08-14 at 11 51 31" src="https://user-images.githubusercontent.com/522834/44084939-64dc95fa-9fb8-11e8-90b9-cbdc2656c227.png">
