### ISSUE TITLE
Payment sit nicht möglich

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#59]
User: Alfred Leonhardt / alfred.leonhardt@t-online.de<br>Joomla: <br>Subscriptions: <br>- PWT ACL - Agency / until: 2018-03-22<br><hr>Fehlermeldung beim Absenden der Bestellung
Paymentserver ist nicht erreichbar

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hi Alfred,

Thank you for contacting us. There is an issue with the payment provider, but we applied a suggested workaround, so the payments options are visible again and the checkout should work.

Apologizes for the inconvenience!

Sander
