### ISSUE TITLE
PWT ACL

### ISSUE THREAD

**Issue by pwtextensions** [perfectwebteam/pwtextensions#60]
User: Dick Speksnijder / info@D56-WebDesign.nl<br>Joomla: <br>Subscriptions: <br>- PWT SEO - Business / until: 2018-11-20<br>- PWT ACL - Agency / until: 2018-08-30<br><hr>Goedemorgen,

Ik heb al sinds 2013 een subscription op (PWT) ACL. Jaarlijks kreeg ik enkele weken voordat de jaar periode af liep een mailtje om te verlengen. Deze mail heb ik dit jaar niet gekregen, of gemist.
Vandaag kreeg ik een mail dat mijn subscription is verlopen. Al ik nu ga verlengen betaal ik de volle prijs.
Is er nog iets te regelen dat ik ACL tegen een gereduceerde prijs kan aanschaffen?

Ik hoor het graag.

Met vriendelijke groet,

Dick Speksnijder
D56 WebDesign

**Comment by sanderpotjer** [comment]
@pwtextensions 
Hallo Dick,

Dank voor je bericht. Dat is uiteraard te regelen! Als je de website bezoekt via https://extensions.perfectwebteam.com/?coupon=ACLRENEWAL dan krijg je bij het bestellen van een PWT subscription automatisch de normale renewal korting.

Groeten, Sander

**Comment by pwtextensions** [comment]
Hallo Sander,

Dank je wel en super dat je dit mogelijk maakt.
Ik zal volgend jaar om deze tijd extra alert zijn om tijdig te verlengen.

Groeten, Dick
